/*
Magnitude Analysis
Purpose: Compare the size of key metrics across different segments (e.g., countries, gender, categories) to identify trends and opportunities for optimization.
*/

-- Find the total number of customers per country
SELECT country, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find the total number of customers by gender
SELECT gender, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT category, COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- Obtain the average cost in each category
SELECT category, AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- Obtain the total revenue generated for each category
SELECT p.category, SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Obtain the total revenue generated by each customer
SELECT DISTINCT c.customer_id, c.first_name, c.last_name, SUM(s.sales_amount) AS total_revenue_per_customer
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c ON s.customer_key = c.customer_key
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_revenue_per_customer DESC

-- Obtain the distribution of items sold across different countries
SELECT country, SUM(quantity) AS items_sold
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c ON s.customer_key = c.customer_key
GROUP BY country 
ORDER BY items_sold DESC
